language: objective-c
osx_image: xcode7
script:
    xctool 
    -workspace Example/Example.xcworkspace
    -scheme MUKScrollTrigger 
    -sdk iphonesimulator
    build 
    CODE_SIGN_IDENTITY="" 
    CODE_SIGNING_REQUIRED=NO
notifications:
    email: false